# Generated by Django 2.2.1 on 2019-07-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
